### ISSUE TITLE
[Tech]: Add status subscription

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-android#12]
### Problem statement

Android Sora app can stays in memory a long time and user could not check his status without killing the app. Duplicates https://github.com/sora-xor/sora-card-ios/issues/5

### Definition of Done

- [ ] card kycStatus is updated without having the restart the app

**Comment by Tieumsan** [comment]
@bgodlin is it kycStatus or verificationStatus ?

**Comment by AmadeyKuspakov** [comment]
How do we want to allow to perform kyc status update? (At which screen, and based on what action) We can for example make swipe to refresh mechanics (such as in google chrome), or make it more manual by adding a button for update, or we can period based server polling
