### ISSUE TITLE
Perform formatting of an autofilled phone number

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/sora-card-android#123]
When user uses phone number autofill, extra symbols don't let to proceed. I think formatting should be berformed or autofill switched off

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVNWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb134e0ee03dd14371f80dc5ae9d11fb806c8268/photo_2023-09-13%2014.29.29.jpeg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVdWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dfeb1d725994ba1bc1aa5fa1e44f6c530d862725/photo_2023-09-13%2014.29.26.jpeg)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8a9ffd13e7962e1a074fbcb060d33add3638ae5d/IMG_9099.MP4)

**Comment by bgodlin** [comment]
Same as https://github.com/sora-xor/sora-card-ios/issues/90#issuecomment-1787259868
