### ISSUE TITLE
Revise the KYC process flow.

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-android#13]

**Comment by spitsynval** [comment]
https://www.figma.com/file/Rqm3Y2XAq3pg0zfProoaqe/%F0%9F%9A%A7-SORA-Wallet-Design-WIP?node-id=0%3A1&t=w5L1Kk88b4ijocJE-1

**Comment by AmadeyKuspakov** [comment]
- [ ] Implement NotEnoughXor screen
- [ ] Fix minor inconsistencies in text according to design
- [ ] Fix navigation conditions in KYC flow
