### ISSUE TITLE
 Improving UI for the transitional phase between Verified KYC and Provisioned IBAN

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-android#131]

**Comment by bgodlin** [comment]
https://github.com/sora-xor/sora-card/issues/99#issuecomment-1737452010

**Comment by bgodlin** [comment]
https://github.com/sora-xor/sora-card/issues/99#issuecomment-1764019824

**Comment by ra9mls** [comment]
Check the clicking behaviour 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU44QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e511f6f4b3fe316847e62df390f0ca0bb6e4ba9b/video_2023-10-27_17-07-05.mp4)
