### ISSUE TITLE
Changing the logic of obtaining EUR equivalent in XOR

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-android#14]
See details in https://github.com/soramitsu/sora-card-backend/issues/147

**Comment by Tieumsan** [comment]
@bgodlin is it still actual ?

**Comment by bgodlin** [comment]
> @bgodlin is it still actual ?

Subject to validation by the developers @Tieumsan

**Comment by bgodlin** [comment]
@arvifox could you kindly provide an update on the status of this matter?

**Comment by ra9mls** [comment]
Related task: https://github.com/soramitsu/sora-card-backend/issues/354
