### ISSUE TITLE
[Tech]: Open keyboard immediately when user opens Verify your phone number screen

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-android#181]
### Problem statement

User should tap on Phone number field

https://github.com/sora-xor/sora-card-android/assets/17094492/50303e79-6f62-4c7f-b063-4522a56d28a8

### Acceptance Criteria

When user opens Verify your phone number screen
Then he sees opened keyboard

### Definition of Done

When user opens Verify your phone number screen he sees opened keyboard

**Comment by Trezeguet1** [comment]
Verified on 3.8.4.0 Soralution version.
