### ISSUE TITLE
[Bug]: [BE] - "Log in or Sign up" button is still not active during Get SORA Card

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-android#192]
### Preconditions

Fresh install

### Steps to reproduce

1. Go to the wallet tab
2. Get SORA Card

### Actual behavior

"Log in or Sign up" button is still not active during Get SORA Card.

![telegram-cloud-photo-size-2-5258038421807552330-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/37663f2e-9ddb-4ac3-bc7f-3026d0b0bddd)

### Expected behavior

"Log in or Sign up"  and "I already have a card" buttons should be active to continue Get SORA Card flow.

NOTE: I'm worried when the bug will be fixed when the buttons are still unavailable, we know for sure this problem is related to the backend or only to the PV side or is it related to credentials, we need to find out
### Environment

{"label"=>"Development"}

### OS version

Android 13

### Additional context

Soralution version

**Comment by Trezeguet1** [comment]
![telegram-cloud-photo-size-2-5273915807799302848-y](https://github.com/sora-xor/sora-card-android/assets/51509139/35f1aab8-74a5-4d00-b320-1d442fcb43dc)

**Comment by arvifox** [comment]
fixed

**Comment by Trezeguet1** [comment]
Verified on 3.8.6.4 version.
