### ISSUE TITLE
[Bug]: [Android] Get SORA Card - 500 error appears when tapping on the “see the list” link 

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-android#193]
### Preconditions

Fresh install

### Steps to reproduce

1.Go to the wallet tab
2.Get SORA Card
3. Tap on the “see the list” link 

### Actual behavior

 Get SORA Card - 500 error appears when tapping on the “see the list” link.
 
 
![telegram-cloud-photo-size-2-5258266634894825952-y](https://github.com/sora-xor/sora-card-android/assets/51509139/e3e49bb2-ba4c-439f-a1aa-fad5e7a517a4)

### Expected behavior

 Get SORA Card - There should be redirect to the  Blacklist page after tapping on the “see the list” link.

### Environment

{"label"=>"Development"}

### OS version

Android 13

### Additional context

Soralution version

**Comment by arvifox** [comment]
fixed

**Comment by Trezeguet1** [comment]
Verified on 3.8.6.4 version.
