### ISSUE TITLE
Android - See X1 transaction status

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-android#22]
As a <ins>user that is trying to buy XOR with fiat</ins> I want to <ins>see the status of my transaction with the exchange (X1)</ins> so that <ins>I can see if my transaction is still being processed, has been successful or rejected</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SC-19

**Comment by bgodlin** [comment]
https://github.com/sora-xor/sora-card/issues/14#issuecomment-1788809253
