### ISSUE TITLE
Android - UI for SORA Card card

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-android#56]
Add the SORA Card card to provide an appealing enough SORA Card hub.<br/>

Only implement the UI for the SORA Card card:

- SORA Card image
- Greyed _Show details_ button
- Text (precise what to display instead of the amount)
- Greyed _Top up/Transfer/Exchange/Freeze_ buttons

<br/> **Design** : https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10297&mode=design&t=T0MFEg0U4SNF13CE-0

**Comment by ra9mls** [comment]
Waiting the Share and Copy buttons.

**Comment by AmadeyKuspakov** [comment]
@ra9mls @Tieumsan What action do we want to tie the button with? Sharing of only IBAN, or also BICSwift? And do we want to share it as text copied to clipboard, or as a constructed PDF file?

**Comment by Tieumsan** [comment]
@AmadeyKuspakov for now only sharing the IBAN. We will create another task in the future depending on the business requirements. 
Thanks for asking to precise this.

**Comment by ra9mls** [comment]
After app kill with Card hub, user have to tap Card button and load the Success status.

**Comment by ra9mls** [comment]
Failed status stays on the main screen after logout.
