### ISSUE TITLE
[Tech]: Remove test data from UI

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-android#58]
### Problem statement

We added additional information in the UI to make it easier to test on the test application (SORAlution).
We need to remove them for the release on production.

### Definition of Done

- [x] Remove the test credentials labels
    * Phone number (https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501-11483&mode=design&t=A0ohft3b4aAUnwyx-0)
    * OTP (https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501-11497&mode=design&t=A0ohft3b4aAUnwyx-0)

**Comment by ra9mls** [comment]
Will checked with prod creds build
